x-core-service: &core-service
  networks: [ fpm-net ]
  profiles:
    - core
    - mgr-components
    - app-platform-minimal

###########################################
####---- Infrastructure containers ----####
###########################################
services:
  db:
    <<: *core-service
    container_name: db
    image: postgres:16-alpine
    networks: [ fpm-net ]
    profiles:
      - core
      - mgr-components
      - app-platform-minimal
    environment:
      PGUSER: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      OKAPI_DB_PASSWORD: ${OKAPI_DB_PASSWORD}
      MGR_APPLICATIONS_DB_PASSWORD: ${MGR_APPLICATIONS_DB_PASSWORD}
      MGR_TENANTS_DB_PASSWORD: ${MGR_TENANTS_DB_PASSWORD}
      MGR_TENANT_ENTITLEMENTS_DB_PASSWORD: ${MGR_TENANT_ENTITLEMENTS_DB_PASSWORD}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KONG_DB_PASSWORD: ${KONG_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka:
    <<: *core-service
    container_name: kafka
    image: apache/kafka-native:4.3.1
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: INTERNAL://:9092,LOCAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,LOCAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_HOURS: -1
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/9092'" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 10s

  vault:
    <<: *core-service
    container_name: vault
    image: folio-vault:1.13.3
    volumes:
      - vault-data:/vault/data:rw
    cap_add: [ IPC_LOCK ]
    ports:
      - "8200:8200"
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      timeout: 10s
      retries: 30
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      KC_ADMIN_CLIENT_ID: ${KC_ADMIN_CLIENT_ID}
      KC_ADMIN_CLIENT_SECRET: ${KC_ADMIN_CLIENT_SECRET}

  kafka-ui:
    <<: *core-service
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_JMXPORT: 9997

networks:
  fpm-net:
    name: folio-platform-minimal
    driver: bridge

volumes:
  db: { }
  vault-data: { }
  kafka-data: { }
