x-keycloak-service: &keycloak-service
  image: folioci/folio-keycloak:latest
  networks: [ fpm-net ]
  env_file: [ env/keycloak.env ]
  profiles: [ keycloak-cluster ]
  depends_on:
    db:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
    interval: 30s
    timeout: 5s
    retries: 20
  deploy:
    resources:
      limits:
        cpus: 1.0
        memory: 1200m
      reservations:
        cpus: 1.0
        memory: 1200m

#############################################
####---- Keycloak cluster containers ----####
#############################################
services:
  keycloak:
    container_name: keycloak
    networks: [ fpm-net ]
    image: nginx
    profiles:
      - core
      - mgr-components
      - app-platform-minimal
      - app-notification
      - app-core-storage
      - keycloak-cluster
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      keycloak-s0:
        condition: service_healthy
    volumes:
      - ./nginx/keycloak-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://keycloak:8080/realms/master || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 15


  keycloak-s0:
    <<: *keycloak-service
    container_name: keycloak-s0
    profiles:
      - core
      - mgr-components
      - app-platform-minimal
      - app-notification
      - app-core-storage
      - keycloak-cluster
    ports:
      - "18081:8080"

  keycloak-s1:
    <<: *keycloak-service
    container_name: keycloak-s1
    ports:
      - "18082:8080"

  keycloak-s2:
    <<: *keycloak-service
    container_name: keycloak-s2
    ports:
      - "18083:8080"
